from django.urls import path
from store import views

urlpatterns = [
    path("", views.health),
    path("api/", views.api_root),
    path("api/categories/", views.categories),
    path("api/visitors/track/", views.visitor_track),
    path("api/projects/", views.public_projects),
    path("api/projects/<slug:slug>/", views.public_project),
    path("api/projects/<slug:slug>/comments/", views.project_comments),
    path("api/projects/<slug:slug>/reports/", views.project_reports),
    path("api/projects/<slug:slug>/events/", views.project_event),

    path("api/dev/register/", views.dev_register),
    path("api/dev/verify-email/", views.dev_verify_email),
    path("api/dev/resend-code/", views.dev_resend_code),
    path("api/dev/login/", views.dev_login),
    path("api/dev/password-reset/", views.dev_password_reset),
    path("api/dev/password-reset/confirm/", views.dev_password_reset_confirm),
    path("api/dev/me/", views.dev_me),
    path("api/dev/dashboard/", views.dev_dashboard),
    path("api/dev/projects/", views.dev_projects),
    path("api/dev/projects/<int:project_id>/", views.dev_project_detail),
    path("api/dev/projects/<int:project_id>/stats/", views.dev_project_stats),
    path("api/dev/projects/<int:project_id>/comments/", views.dev_project_comments),
    path("api/dev/messages/", views.dev_messages),
    path("api/dev/messages/<int:message_id>/", views.dev_message_detail),
    path("api/dev/messages/<int:message_id>/reply/", views.dev_message_reply),

    path("api/admin/login/", views.admin_login),
    path("api/admin/dashboard/", views.admin_dashboard),
    path("api/admin/developers/", views.admin_developers),
    path("api/admin/developers/<int:user_id>/suspend/", views.admin_developer_suspend),
    path("api/admin/developers/<int:user_id>/reactivate/", views.admin_developer_reactivate),
    path("api/admin/developers/<int:user_id>/", views.admin_developer_detail),
    path("api/admin/developers/<int:user_id>/messages/", views.admin_developer_message),
    path("api/admin/publications/", views.admin_publications),
    path("api/admin/publications/<int:project_id>/", views.admin_publication_detail),
    path("api/admin/publications/<int:project_id>/approve/", views.admin_publication_approve),
    path("api/admin/publications/<int:project_id>/feature/", views.admin_publication_feature),
    path("api/admin/publications/<int:project_id>/reject/", views.admin_publication_reject),
    path("api/admin/publications/<int:project_id>/suspend/", views.admin_publication_suspend),
]
